include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - build/**
    - lib/**/*.freezed
    - lib/**/*.g.dart
linter:
  rules:
    eol_at_end_of_file: true
    file_names: true
    implementation_imports: true
    package_prefixed_library_names: true
    prefer_single_quotes: true
    public_member_api_docs: false
    require_trailing_commas: true
    sort_constructors_first: true
