name: littlehelpbook_api
version: 1.0.0+1
publish_to: none
description: The Little Help Book API project, built with Dart Frog.
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  dart_airtable: ^1.1.0
  dart_frog: ^0.3.0
  envied: ^0.3.0
  fimber: ^0.6.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  result_type: ^0.2.0
  riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1
dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  riverpod_generator: ^1.2.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
